server:
  port: 8766

spring:
  application:
    name: product-view-service-feign
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
